# Optimization: principles and algorithms

Bierlaire, M. (2015). *Optimization: Principles and Algorithms.* EPFL Press.

# Chapter 9: Quadratic problems

This notebook replicates the examples from the book, using the python package optimization_book. The numbering of the algorithms, tables and page refer to the book.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import optimization_book.unconstrained as unc
import optimization_book.exceptions as excep

### Algorithm 9.1: quadratic problems: direct solution

Example 9.8: $Q=\left(\begin{array}{cccc} 1& 1 & 1 & 1 \\ 1 & 2 & 2 & 2 \\ 1 & 2 & 3 & 3 \\ 1 & 2 & 3 & 4\end{array}\right)$, $b=\left(\begin{array}{c}-4 \\ -7 \\ -9 \\ -10\end{array}\right)$

In [2]:
Q = np.array([[1, 1, 1, 1],
              [1, 2, 2, 2],
              [1, 2, 3, 3],
              [1, 2, 3, 4]])
b = np.array([-4, -7, -9, -10])
s = unc.quadraticDirect(Q, b)
print(s)

[1. 1. 1. 1.]


### Algorithm 9.2: Conjugate gradient method

Run the algorithm from $x_0=\left(\begin{array}{c}5 \\ 5 \\ 5 \\ 5 \end{array}\right)$.

In [3]:
x0 = np.array([5.0, 5.0, 5.0, 5.0])
x, iters = unc.conjugateGradient(Q, b, x0)
print(x)

[1. 1. 1. 1.]


Calculate the gradient, to check that it is indeed numerically close to 0.

In [4]:
print(Q @ x + b)

[-1.63336011e-12 -3.06865644e-12 -4.13535872e-12 -4.70556927e-12]


Table 9.1, page 231.

In [5]:
def oneIter(k, iter):
    """Print the information about one iteration

    :param k: iteration number
    :type k: int

    :param iter: information about the iteration: xk, gk, dk, alphak, betak
    :type iter: tuple(np.array, np.array, np.array, float, float)
    """
    for i in range(4):
        if i == 0:
            print(
                f'{k}\t'
                f'{iter[0][i]:+E}\t'
                f'{iter[1][i]:+E}\t'
                f'{iter[2][i]:+E}\t'
                f'{iter[3]:+E}\t'
                f'{iter[4]:+E}'
            )
        else:
            print(
                f'\t'
                f'{iter[0][i]:+E}\t'
                f'{iter[1][i]:+E}\t'
                f'{iter[2][i]:+E}'
            )


In [6]:
print("k\txk\t\tgk\t\tdk\t\talphak\t\tbetak")
for k, it in enumerate(iters):
    print(85*'-')
    oneIter(k, it)
   

k	xk		gk		dk		alphak		betak
-------------------------------------------------------------------------------------
0	+5.000000E+00	+1.600000E+01	-1.600000E+01	+1.207658E-01	+0.000000E+00
	+5.000000E+00	+2.800000E+01	-2.800000E+01
	+5.000000E+00	+3.600000E+01	-3.600000E+01
	+5.000000E+00	+4.000000E+01	-4.000000E+01
-------------------------------------------------------------------------------------
1	+3.067747E+00	+1.508100E+00	-1.525788E+00	+1.029534E+00	+1.105469E-03
	+1.618557E+00	+9.484536E-01	-9.794067E-01
	+6.524300E-01	-2.297496E-01	+1.899527E-01
	+1.693667E-01	-1.060383E+00	+1.016164E+00
-------------------------------------------------------------------------------------
2	+1.496896E+00	+1.706557E-01	-1.976757E-01	+2.371723E+00	+1.770889E-02
	+6.102242E-01	-1.555851E-01	+1.382409E-01
	+8.479928E-01	-9.204998E-02	+9.541383E-02
	+1.215542E+00	+1.234923E-01	-1.054971E-01
-------------------------------------------------------------------------------------
3	+1.028064E+00	+5.777961

An error is triggered if the matrix is not definite positive. Here, $Q=\left(\begin{array}{cccc} 1& 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \\ 13 & 14 & 15 & 16\end{array}\right)$

In [7]:
Q = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8],
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])
b = np.array([-4, -7, -9, -10])
x0 = np.array([5.0, 5.0, 5.0, 5.0])
try:
    x, iters = unc.conjugateGradient(Q, b, x0)
except excep.optimizationError as e:
    print(f'Exception raised: {e}')

Exception raised: The matrix must be positive definite
